#!/usr/bin/env bash
# Bash script that displays information about subdomains.
dig_me=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1)
ip=$(echo "$dig_me" | awk -F" " '{print $5}')
rec_type=$(echo "$dig_me" | awk -F" " '{print $4}')
sub_ip () {
  echo "The subdomain $2 is a $rec_type record and points to $ip"
}
if [ "$#" == 2 ]; then
  sub_ip "$1" "$2"
elif [ "$#" == 1 ]; then
  sub_ip "$1" "www"
  sub_ip "$1" "lb-01"
  sub_ip "$1" "web-01"
  sub_ip "$1" "web-02"
fi
