#!/usr/bin/env bash
# Bash script that displays information about subdomains.
subdom=("www" "lb-01" "web-01" "web-02")
dig_me=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1)
ip=$(echo "$dig_me" | awk -F" " '{print $5}')
rec_type=$(echo "$dig_me" | awk -F" " '{print $4}')
if [ "$#" == 2 ]; then
  echo "The subdomain $2 is a $rec_type record and points to $ip"
elif [ "$#" == 1 ]; then
  for sub in "${subdom[@]}"; do
    echo "The subdomain $sub is a $rec_type record and points to $ip"
  done
fi
