#!/usr/bin/env bash
# nginx on your web-01
apt-get update
apt-get -y install nginx
echo 'Hello World' > /var/www/html/index.html
sed -i 's/listen\s*80/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx start
