#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
# Create a new configuration file for the redirection
sudo tee /etc/nginx/sites-enabled/default << EOF
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;;

    server_name 54.144.144.194;

    location /redirect_me {
        return 301 https://oluwatobialure.hashnode.dev;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Test the Nginx configuration and restart the server
sudo nginx -t && sudo service nginx restart
