#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo tee /etc/nginx/sites-enabled/default > /dev/null << EOF
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm;
    server_name 54.144.144.194;
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://oluwatobialure.hashnode.dev;
    }
}
EOF

# Test the Nginx configuration and restart the server
sudo nginx -t && sudo service nginx restart
