#!/usr/bin/env bash
# Update package list and Install nginx

sudo apt-get update
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Configure custom 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo sed -i '/error_page 404/ a\        root /var/www/html;\n' /etc/nginx/sites-available/default

# Configure redirection
sudo sed -i '/listen 80 default_server;/ a\        return 301 https://oluwatobialure.hashnode.dev$request_uri;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

