#!/usr/bin/env bash
# Configure identical server with custom header
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo tee /etc/nginx/sites-enabled/default << EOF
server {
    listen 80 default_server
    listen [::]:80 default_server
    root /var/www/html
    index index.html index.htm index.nginx-debian.html
    server_name _
    add_header X-Served-By \$hostname
    location / {
        try_files \$uri \$uri/=404;
    }
    location /redirect_me {
        return 301 https://oluwatobialure.hashnode.dev;
    }
    error_page 404 /404.html
    location = /404.html {
        internal;
    }
}
EOF
sudo nginx -t && sudo service nginx restart
