#!/usr/bin/env bash
# Configure identical server with custom header
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo tee -a /etc/haproxy/haproxy.cfg << EOF
frontend http-in
	bind *:80
	default_backend zettai
backend zettai
	balance roundrobin
	server web-01 54.144.144.194
	server web-02 100.25.140.47
EOF
sudo service haproxy enable
sudo service haproxy restart
