#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -uroot --password="$1" --all-databases > backup.sql
YEAR=$(date +"%Y")
MONTH=$(date +"%m")
DAY=$(date +"%d")
ARCHIVE="$DAY-$MONTH-$YEAR.tar.gz"
tar -cvzf "$ARCHIVE" backup.sql
