#!/usr/bin/env bash
# Trapping a signal

echo $BASHPID > /var/run/myscript.pid
while ((1))
do
  echo "To infinity and beyond"
  sleep 2
  trap "echo 'I hate the kill command' && rm /var/run/myscript.pid" SIGTERM
  trap "echo 'Y U no love me?!'" SIGINT
  trap "rm /var/run/myscript.pid" SIGQUIT
done
