#!/usr/bin/env bash
# Displays the content of the file /etc/passwd

while IFS=":" read -r username gid home shell uid passwd user_info
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $user_info"
done < /etc/passwd
