#!/usr/bin/env bash
# Prints text conditionally

while ((a++ < 10))
do
  if [ "$a" -eq 4 ]
  then
    echo "bad luck"
  elif [ "$a" -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
done
