#!/usr/bin/env bash
# Prints text conditionally using case

while ((a++ < 20))
do
  case $a in

    4)
	  echo "$a"
	  echo "bad luck from China"
	  ;;
	9)
	  echo "$a"
	  echo "bad luck from Japan"
	  ;;
	17)
	  echo "$a"
	  echo "bad luck from Italy"
	  ;;
	*)
	  echo "$a"
	  ;;
  esac
done
